### PR TITLE
emote

### PR DESCRIPTION
**Pull request by chiamil**

### CODE REVIEW

**Comment by nq5** [comment]
Have you tested? Looks like [emotes.go](https://github.com/vxhllc/MovieNight/blob/master/emotes.go) auto-loads any in /static/emotes but worth making sure since we don't have any tests set up

**Comment by chiamil** [comment]
> Have you tested? Looks like [emotes.go](https://github.com/vxhllc/MovieNight/blob/master/emotes.go) auto-loads any in /static/emotes but worth making sure since we don't have any tests set up

professionalism is key but i do not care. just push it to master.

**Comment by nq5** [comment]
fuck it we ball

**Comment by nq5** [comment]
@1488voxo commit the logon page changes and lets test this before closing

**Comment by 1488voxo** [comment]
works.

**Comment by nq5** [comment]
DOES IT REALLY

**Comment by 1488voxo** [comment]
yes you mongoloid, i told u already it works.

**Comment by nq5** [comment]
but does it **work**

**Pull request merged**
